name: Publish Docker Image to DockerHub

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@sudhirsonawane5@gmail.com
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/dockerhub-connection

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dockerhub-connection
